import { BlockMath } from 'react-katex'
import { ArrowRight, Pause, Play } from 'lucide-react'
import { motion } from 'motion/react'
import { equations } from '../content/equations'
import { attentionForQuery } from '../lib/simulations'
import { SlideFrame } from './shared'

export type AttentionPhase = 'column' | 'row' | 'alternating' | 'icl'

export function AttentionSlide({ phase, setPhase, playing, setPlaying }: { phase: AttentionPhase; setPhase: (value: AttentionPhase) => void; playing: boolean; setPlaying: (value: boolean) => void }) {
  const phases: { id: AttentionPhase; label: string; title: string; explanation: string; formula: string }[] = [
    { id: 'column', label: 'column attention', title: 'Look down a column', explanation: 'Cells in one feature compare across rows. The model can learn distributional facts such as scale, skew, extremes, or category patterns.', formula: equations.columnAttention },
    { id: 'row', label: 'row attention', title: 'Look across a row', explanation: 'Features within one policyholder interact. The model can combine age, vehicle, miles, and region before asking what they imply together.', formula: equations.rowAttention },
    { id: 'alternating', label: 'alternating attention', title: 'Column, then row, then repeat', explanation: 'TabPFN-v2 and TabPFN-2.5 alternate the two views so information can travel across the table without treating every cell as an isolated scalar.', formula: equations.alternating },
    { id: 'icl', label: 'compression then ICL', title: 'Compress, then let the query read context', explanation: 'TabICL names its stages TFcol, TFrow, and TFicl: columns become distribution-aware embeddings, rows become fixed-width vectors, then the query reads labeled rows. A readout converts the weighted evidence into the output cell.', formula: equations.tableNextLabel },
  ]
  const activePhase = phases.find((item) => item.id === phase) ?? phases[0]
  const queryWeights = attentionForQuery(4, 1)
  return <SlideFrame number="03" kicker="In context / the mechanics of attention" tone="mint"><div className="slide-two-column"><div><h2 className="slide-title">Attention is a routing rule for evidence.</h2><p className="slide-lead">The query is not “looking” in a human sense. Each attention head computes compatibility between a query vector and key vectors, then uses the resulting weights to mix value vectors.</p><div className="rounded-[14px] border border-[#a8d2c3] bg-[#dfeee7] p-5"><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-[#2f8175]">the shared engine</p><BlockMath math={equations.attention} /><p className="text-xs leading-5 text-[#53606a]">Large weights route more of the value information into the next representation. The mask decides which comparisons are legal.</p></div><div className="mt-5 grid gap-2">{phases.map((item) => <button key={item.id} onClick={() => setPhase(item.id)} className={`flex items-center justify-between rounded-[10px] border px-4 py-3 text-left transition-colors ${phase === item.id ? 'border-[#3e8d7e] bg-[#dfeee7]' : 'border-[#1e2a35]/10 bg-[#fffdf8] hover:bg-[#f5f2ea]'}`}><span><span className="block text-sm font-semibold">{item.label}</span><span className="mt-1 block text-xs text-[#74808a]">{item.title}</span></span><ArrowRight size={15} className={phase === item.id ? 'text-[#2f8175]' : 'text-[#a4a9aa]'} /></button>)}</div></div><div className="surface-panel bg-[#fffdf8] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-[#74808a]">animated attention map</p><p className="mt-1 text-xl font-semibold">{activePhase.title}</p></div><button onClick={() => setPlaying(!playing)} className="inline-flex items-center gap-2 rounded-full bg-[#1e2a35] px-3 py-2 text-xs font-semibold text-[#f5f2ea]">{playing ? <Pause size={14} /> : <Play size={14} />} {playing ? 'pause' : 'play'} sequence</button></div><AttentionAnimation phase={phase} queryWeights={queryWeights} /><div className="mt-5 rounded-[10px] bg-[#f5f2ea] p-4"><p className="text-sm font-semibold">{activePhase.explanation}</p><div className="mt-3 overflow-x-auto"><BlockMath math={activePhase.formula} /></div></div><PredictionReadout phase={phase} /></div></div></SlideFrame>
}

function AttentionAnimation({ phase, queryWeights }: { phase: AttentionPhase; queryWeights: number[] }) {
  const rows = ['A', 'B', 'C', 'Q']
  const columns = ['age', 'vehicle', 'miles']
  return <div className="mt-7 rounded-[12px] border border-[#1e2a35]/10 bg-[#f5f2ea] p-4"><div className="grid grid-cols-[34px_repeat(3,1fr)_64px] items-center gap-2 text-center font-mono text-[9px] uppercase tracking-[0.08em] text-[#8a9295]"><span />{columns.map((column) => <span key={column}>{column}</span>)}<span>output</span>{rows.map((row, rowIndex) => <div key={row} className="contents"><span className={`text-left font-semibold ${row === 'Q' ? 'text-[#3869a8]' : 'text-[#74808a]'}`}>{row}</span>{columns.map((column, columnIndex) => { const active = phase === 'column' ? columnIndex === 1 : phase === 'row' ? rowIndex === 3 : phase === 'alternating' ? (rowIndex + columnIndex) % 2 === 0 : rowIndex === 3; return <motion.span key={`${row}-${column}`} className={`flex h-12 items-center justify-center rounded-[8px] border font-mono text-[10px] transition-colors ${active ? 'border-[#3e8d7e] bg-[#bfe0d3] text-[#1e5e55]' : 'border-[#1e2a35]/8 bg-[#fffdf8] text-[#74808a]'}`} animate={{ scale: active ? 1.05 : 1, opacity: active ? 1 : 0.62 }} transition={{ duration: 0.35 }}>{rowIndex === 3 && columnIndex === 2 ? '?' : `${[22, 11, 18, 39, 8, 15, 51, 9, 16, 64, 5, 6][rowIndex * 3 + columnIndex]}`}</motion.span> })}<motion.span className={`flex h-12 items-center justify-center rounded-[8px] border font-mono text-[10px] font-semibold ${row === 'Q' ? 'border-[#d64e3b] bg-[#fbe4dc] text-[#d64e3b]' : 'border-[#1e2a35]/8 bg-[#fffdf8] text-[#b0b5b4]'}`} animate={{ opacity: row === 'Q' ? 1 : phase === 'icl' ? 0.92 : 0.45 }}>{row === 'Q' ? `${Math.round((0.48 + queryWeights[1] * 0.4) * 100)}%` : '—'}</motion.span></div>)}</div><div className="mt-4 flex flex-wrap items-center gap-4 font-mono text-[9px] uppercase tracking-[0.08em] text-[#74808a]"><span className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded bg-[#bfe0d3]" /> active route</span><span className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded border border-[#d64e3b] bg-[#fbe4dc]" /> predicted target</span></div></div>
}

function PredictionReadout({ phase }: { phase: AttentionPhase }) {
  const value = phase === 'column' ? 54 : phase === 'row' ? 61 : phase === 'alternating' ? 65 : 68
  return <><div className="mt-5 grid gap-3 sm:grid-cols-[1fr_190px] sm:items-center"><div><p className="font-mono text-[10px] uppercase tracking-[0.12em] text-[#74808a]">the output cell is still missing</p><p className="mt-2 text-sm leading-6 text-[#53606a]">Attention changes the hidden representation. The final head maps that representation to a probability for the held-out claim label.</p></div><div className="rounded-[12px] border border-[#efb2a2] bg-[#fbe4dc] p-4"><p className="font-mono text-[9px] uppercase tracking-[0.1em] text-[#8a4d43]">P(claim = 1)</p><p className="mt-1 font-serif text-4xl text-[#d64e3b]">{value}%</p><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/70"><motion.div className="h-full rounded-full bg-[#d64e3b]" animate={{ width: `${value}%` }} /></div></div></div><AttentionPipeline phase={phase} /></>
}

function AttentionPipeline({ phase }: { phase: AttentionPhase }) {
  const activeStep = phase === 'column' ? 0 : phase === 'row' ? 1 : phase === 'alternating' ? 2 : 3
  const steps = [
    ['Q · K', 'similarity scores'],
    ['softmax', 'attention weights'],
    ['Σ αV', 'weighted values'],
    ['head', 'logit / probability'],
  ]
  return <div className="mt-5 rounded-[12px] border border-[#1e2a35]/10 bg-[#f5f2ea] p-4"><div className="grid gap-2 sm:grid-cols-4">{steps.map(([label, text], index) => <motion.div key={label} className={`rounded-[9px] border p-3 ${activeStep === index ? 'border-[#3e8d7e] bg-[#dfeee7]' : 'border-[#1e2a35]/8 bg-[#fffdf8]'}`} animate={{ opacity: activeStep === index ? 1 : 0.58, y: activeStep === index ? -2 : 0 }}><p className="font-mono text-xs font-semibold text-[#1e2a35]">{label}</p><p className="mt-1 text-[10px] leading-4 text-[#74808a]">{text}</p></motion.div>)}</div><p className="mt-4 text-[10px] leading-5 text-[#74808a]"><span className="font-mono uppercase tracking-[0.08em] text-[#3869a8]">mask rule:</span> context labels are visible, the query label stays hidden, and no query token can read the held-out answer.</p></div>
}