import type { Claim } from '../types'

export const claims: Claim[] = [
  {
    id: 'v1-pfn',
    sourceId: 'tabpfn-v1',
    family: 'TabPFN',
    kind: 'method',
    claim: 'A PFN learns a prediction algorithm offline on synthetic datasets and uses one forward pass at inference time.',
    context: 'The original paper frames the model as an approximation to a posterior predictive distribution under a chosen prior.',
    metric: 'Method principle',
    regime: 'Synthetic pretraining; clean small classification tables',
    tags: ['prior', 'ICL', 'Bayesian'],
  },
  {
    id: 'v1-limit',
    sourceId: 'tabpfn-v1',
    family: 'TabPFN',
    kind: 'limitation',
    claim: 'The original model was designed for up to 1,000 training rows, 100 numerical features, and 10 classes.',
    context: 'The paper reports weaker performance on categorical features and missing values and quadratic attention cost in the number of inputs.',
    metric: 'Validated operating envelope',
    regime: 'OpenML small-data experiments',
    tags: ['limits', 'small-data'],
  },
  {
    id: 'nature-speed',
    sourceId: 'tabpfn-nature',
    family: 'TabPFN',
    kind: 'paper-result',
    claim: 'TabPFN outperformed prior methods on small tabular datasets while using substantially less training time.',
    context: 'The Nature article reports 2.8 seconds against an ensemble of strong baselines tuned for four hours in its classification setting.',
    metric: 'Classification accuracy and runtime',
    regime: 'Small tabular benchmark; reported paper protocol',
    tags: ['speed', 'benchmark'],
  },
  {
    id: 'nature-extensions',
    sourceId: 'tabpfn-nature',
    family: 'TabPFN',
    kind: 'method',
    claim: 'The model can also support fine-tuning, data generation, density estimation, and reusable embeddings.',
    context: 'These are capabilities of the generative transformer framing, not a guarantee that every downstream task is solved without adaptation.',
    metric: 'Capability extension',
    regime: 'Research extensions',
    tags: ['extensions', 'embeddings'],
  },
  {
    id: '25-scale',
    sourceId: 'tabpfn-2-5',
    family: 'TabPFN-2.5',
    kind: 'paper-result',
    claim: 'TabPFN-2.5 targets tables up to 50,000 rows and 2,000 features and reports strong TabArena performance.',
    context: 'The report compares default and tuned variants against tree models and AutoGluon; its claims should be read with those regimes visible.',
    metric: 'Accuracy, regression error, win rates',
    regime: 'TabArena and internal benchmarks; report claims',
    tags: ['scale', 'benchmark', 'technical-report'],
  },
  {
    id: '25-distill',
    sourceId: 'tabpfn-2-5',
    family: 'TabPFN-2.5',
    kind: 'method',
    claim: 'A fitted TabPFN can be distilled into a dataset-specific MLP or tree ensemble for lower-latency deployment.',
    context: 'The distilled artifact no longer performs in-context learning; it is a separate model tied to the dataset used for distillation.',
    metric: 'Latency and retained predictive performance',
    regime: 'Production-oriented report workflow',
    tags: ['deployment', 'distillation'],
  },
  {
    id: 'tabicl-scale',
    sourceId: 'tabicl-v1',
    family: 'TabICL',
    kind: 'paper-result',
    claim: 'TabICL uses column-then-row attention to compress tables before dataset-wise ICL and is designed for much larger tables.',
    context: 'The paper reports pretraining up to 60,000 samples and practical inference up to 500,000 samples under its memory setup.',
    metric: 'Accuracy, log loss, runtime',
    regime: 'TALENT classification benchmark',
    tags: ['scale', 'architecture', 'ICL'],
  },
  {
    id: 'tabicl-prior',
    sourceId: 'tabicl-v1',
    family: 'TabICL',
    kind: 'method',
    claim: 'TabICL enriches synthetic pretraining with tree-based structural causal models and a curriculum over table size.',
    context: 'The design adds tree-like inductive bias and gradually exposes the model to longer datasets.',
    metric: 'Prior and curriculum design',
    regime: 'Synthetic pretraining',
    tags: ['prior', 'curriculum'],
  },
  {
    id: 'tabicl-v2',
    sourceId: 'tabicl-v2',
    family: 'TabICLv2',
    kind: 'paper-result',
    claim: 'TabICLv2 reports strong performance with a richer synthetic prior, scalable softmax, and optimized pretraining.',
    context: 'The report emphasizes open inference code and weights and compares default settings against tuned or ensembled baselines.',
    metric: 'Improvability, Elo, rank, log loss, RMSE',
    regime: 'TabArena and TALENT; technical report protocol',
    tags: ['benchmark', 'QASSMax', 'technical-report'],
  },
  {
    id: 'tabicl-quantiles',
    sourceId: 'tabicl-v2',
    family: 'TabICLv2',
    kind: 'method',
    claim: 'TabICLv2 regression predicts many quantiles and reconstructs a predictive distribution rather than only a point estimate.',
    context: 'The report describes pinball-loss training, monotonicity correction, tail extrapolation, and derived PDF/CDF/moments.',
    metric: 'Pinball loss and CRPS-style distributional quantities',
    regime: 'Regression; reported and synthetic validation settings',
    tags: ['uncertainty', 'quantiles', 'actuarial'],
  },
  {
    id: 'tabpfn3-architecture',
    sourceId: 'tabpfn-3',
    family: 'TabPFN-3',
    kind: 'method',
    claim: 'TabPFN-3 compresses feature information into fixed-dimensional row representations before row-level ICL.',
    context: 'The report combines efficient inducing attention, row aggregation, QASSMax, row chunking, and a reduced KV cache.',
    metric: 'Memory and inference architecture',
    regime: 'Large-row tabular inference',
    tags: ['scale', 'caching', 'architecture'],
  },
  {
    id: 'tabpfn3-frontier',
    sourceId: 'tabpfn-3',
    family: 'TabPFN-3',
    kind: 'paper-result',
    claim: 'The report evaluates TabPFN-3 on tables up to one million training rows and broader task families.',
    context: 'The million-row and Thinking-mode results are technical-report claims with specific hardware, benchmark, licensing, and API boundaries.',
    metric: 'Elo, rank, runtime, pinball loss',
    regime: 'TabArena, TALENT, internal and extension benchmarks',
    tags: ['scale', 'technical-report', 'caveat'],
  },
]
