import type { PaperSource } from '../types'

export const papers: PaperSource[] = [
  {
    id: 'tabpfn-v1',
    file: 'TabFM.pdf',
    title: 'TabPFN: A Transformer That Solves Small Tabular Classification Problems in a Second',
    authors: 'Hollmann, Muller, Eggensperger, Hutter',
    status: 'Conference paper',
    date: '2022 / v6 2023',
    venue: 'arXiv 2207.01848',
    focus: 'The original prior-data fitted network: synthetic tasks, posterior prediction, and row-token ICL.',
    sourceUrl: 'https://arxiv.org/pdf/2207.01848',
    externalUrl: 'https://arxiv.org/abs/2207.01848',
  },
  {
    id: 'tabpfn-nature',
    file: 'TabFM-2.pdf',
    title: 'Accurate predictions on small data with a tabular foundation model',
    authors: 'Hollmann et al.',
    status: 'Journal article',
    date: 'January 2025',
    venue: 'Nature 637, 319-326',
    focus: 'A peer-reviewed practical demonstration of TabPFN and its extensions on small tabular data.',
    sourceUrl: 'https://doi.org/10.1038/s41586-024-08328-6',
    externalUrl: 'https://doi.org/10.1038/s41586-024-08328-6',
  },
  {
    id: 'tabpfn-2-5',
    file: 'TabFM-2.5.pdf',
    title: 'TabPFN-2.5: Advancing the State of the Art in Tabular Foundation Models',
    authors: 'Grinsztajn et al.',
    status: 'Technical report',
    date: 'November 2025 / v2 February 2026',
    venue: 'arXiv 2511.08667v2',
    focus: 'A larger TabPFN release: richer priors, deeper grouped attention, calibration controls, and distillation.',
    sourceUrl: 'https://arxiv.org/pdf/2511.08667',
    externalUrl: 'https://arxiv.org/abs/2511.08667',
  },
  {
    id: 'tabpfn-3',
    file: 'TabFM-3.pdf',
    title: 'TabPFN-3: Technical Report',
    authors: 'Prior Labs team',
    status: 'Technical report',
    date: 'May 2026 / v2',
    venue: 'arXiv 2605.13986v2',
    focus: 'Compression-then-ICL, long-context attention, row chunking, caching, many-class decoding, and broader data types.',
    sourceUrl: 'https://arxiv.org/pdf/2605.13986',
    externalUrl: 'https://arxiv.org/abs/2605.13986',
  },
  {
    id: 'tabicl-v1',
    file: 'TabICL.pdf',
    title: 'TabICL: A Tabular Foundation Model for In-Context Learning on Large Data',
    authors: 'Qu, Holzmueller, Varoquaux, Le Morvan',
    status: 'Conference paper',
    date: 'ICML 2025',
    venue: 'arXiv 2502.05564',
    focus: 'A scalable column-then-row embedding architecture for large tables and efficient dataset-wise ICL.',
    sourceUrl: 'https://arxiv.org/pdf/2502.05564',
    externalUrl: 'https://arxiv.org/abs/2502.05564',
  },
  {
    id: 'tabicl-v2',
    file: 'TabICL-2.pdf',
    title: 'TabICLv2: A better, faster, scalable, and open tabular foundation model',
    authors: 'Qu, Holzmueller, Varoquaux, Le Morvan',
    status: 'Technical report',
    date: 'February 2026',
    venue: 'arXiv 2602.11139v1',
    focus: 'A richer synthetic prior plus QASSMax, target-aware embeddings, quantile regression, and open scaling work.',
    sourceUrl: 'https://arxiv.org/pdf/2602.11139',
    externalUrl: 'https://arxiv.org/abs/2602.11139',
  },
]

export const paperById = Object.fromEntries(papers.map((paper) => [paper.id, paper]))
